name: "test_config"
models:
  - name: "global_subject_classifier"
    disabled: true
    type: classification
    steps:
      - type: load_csv
        name: data
        path: "../../multitask_training/data_cleaned_manual_combined.csv"
      - type: train_model
        name: training
        dataframe: data.dataframe
        pretrained_model: "bert-base-uncased"
        examples_column: "Question"
        labels_column: "Global Subject"

  - name: "question_intent_classifiers"
    disabled: true
    type: classification
    steps:
      - type: load_csv
        name: data
        path: "../../multitask_training/data_cleaned_manual_combined.csv"
      - type: split_data
        name: split
        dataframe: data.dataframe
        on_column: "Global Subject"
        for_each:
          - type: train_model
            name: training
            dataframe: split.dataframe
            pretrained_model: "bert-base-uncased"
            examples_column: "Question"
            labels_column: "Question Intent"
            resulting_model_name: "question_intent_{on_column}"

  - name: "question_entities_recognition"
    type: ner
    steps:
      - type: ner_spacy
        name: ner_training
        language: "en"
        training_data_path: "../../ner_training/corpus/ner_labels.jsonl"
        training_device: "gpu"
        resulting_model_name: "ner_trained_model"

interactions:
  - type: interaction
    use: "global_subject_classifier"
    name: "global_subject_identification"
    cases:
      "start":
        reply:
          - "Hi! Feel free to ask me anything related to the finite state automaton, and I'll do my best to help."
          - "Hello! How can I assist you with questions about the finite state automaton I've been given?"
          - "Welcome! Got any queries about the finite state automaton I've been given? I'd be happy to help."
          - "Hi there! Feel free to ask any questions regarding the finite state automaton I've been given, and I'll provide support."

      "transition":
        use: "question_intent_transition"
        name: "transition_questions"
        cases:
          - "count"
          - "cycles"
          - "description"
          - "existence_between"
          - "existence_directed"
          - "existence_from"
          - "existence_into"
          - "input"
          - "label"
          - "list"
          - "self_loop"
      "automaton": ""
      "state": ""
      "grammar": " "
      "theory": ""
      "off_topic":
        reply:
          - "Sorry, I don't know how to answer this."
          - "Please, consider rephrasing the question."
  # fallback case
  - type: reply
    reply: "An error has occurred. Please see the attached log: {{log}}"