name: "test_config"
models:
  - name: "global_subject_classifier"
    disabled: false
    type: classification
    steps:
      - type: load_csv
        name: data
        path: "./multitask_training/data_cleaned_manual_combined.csv"
      - type: train_model
        name: training
        dataframe: data.dataframe
        pretrained_model: "bert-base-uncased"
        examples_column: "Question"
        labels_column: "Global Subject"
        train_epochs: 20

  - name: "question_intent_classifiers"
    disabled: false
    type: classification
    steps:
      - type: load_csv
        name: data
        path: "./multitask_training/data_cleaned_manual_combined.csv"
      - type: split_data
        name: split
        dataframe: data.dataframe
        on_column: "Global Subject"
        for_each:
          - type: train_model
            name: training
            dataframe: split.dataframe
            pretrained_model: "bert-base-uncased"
            examples_column: "Question"
            labels_column: "Question Intent"
            resulting_model_name: "question_intent_{on_column}"

  - name: "question_entities_recognition"
    type: ner
    steps:
      - type: ner_spacy
        name: ner_training
        language: "en"
        training_data_path: "./ner_training/corpus/ner_labels.jsonl"
        training_device: "gpu"
        resulting_model_name: "ner_trained_model"

resources:
  # LLM APIs that are not specified in the runner configuration

flows:
  main:
    start_step: "startup message"
    steps:
      startup message:
        type: bot_message
        message: |-
          Hi!
        next_step: input test
      input test:
        type: user_input


interaction:
  use: "global_subject_classifier"
  name: "global_subject_identification"
  cases:
    "start":
      name: "greeting_replies"
      reply:
        - "Hi! Feel free to ask me anything related to the finite state automaton, and I'll do my best to help."
        - "Hello! How can I assist you with questions about the finite state automaton I've been given?"
        - "Welcome! Got any queries about the finite state automaton I've been given? I'd be happy to help."
        - "Hi there! Feel free to ask any questions regarding the finite state automaton I've been given, and I'll provide support."
    "transition":
      use: "question_intent_transition"
      name: "transition_questions"
      cases:
        "count":
          name: "Count Reply"
          reply: "Count Reply"
        "cycles":
          #?????
          name: "Cycles Reply"
          reply: "Cycles Reply"
        "description":
          name: "Desc Reply"
          reply: "Desc Reply"
        "existence_between":
          name: "Ex Reply"
          reply: "Ex Reply"
        "existence_directed":
          name: "ExD Reply"
          reply: "ExD Reply"
        "existence_from":
          name: "ExF Reply"
          reply: "ExF Reply"
        "existence_into":
          name: "ExI Reply"
          reply: "ExI Reply"
        "input":
          name: "I Reply"
          reply: "I Reply"
        "label":
          name: "L Reply"
          reply: "L Reply"
        "list":
          name: "Li Reply"
          reply: "Li Reply"
        "self_loop":
          name: "Lo Reply"
          reply: "Lo Reply"
    "automaton":
      name: "Automaton Reply"
      reply: "Automaton Reply"
    "state":
      name: "State Reply"
      reply: "State Reply"
    "grammar":
      name: "Grammar Reply"
      reply: "Grammar Reply"
    "theory":
      name: "Theory Reply"
      reply: "Theory Reply"
    "off_topic":
      name: "off_topic_replies"
      reply:
        - "Sorry, I don't know how to answer this."
        - "Please, consider rephrasing the question."